What is Pandas?
Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('../sample.csv')


In [3]:
df.head()

sno             name   age   salary     designation        mobile
0    1    shabeeh abaas  23.0  $20,000         manager  9.140098e+09
1    2  kashish agrawal  21.0  $23,000        manager   3.242343e+08
2    3     nisha shukla  22.0  $32,000  region manager  2.903482e+09
3    4     kriti rajput  22.0   $3,333             NaN           NaN
4    5     deepak gupta  23.0  $33,000         manager  2.343243e+08

In [4]:
# df.notnull()         #to check not null values
# df.isnull()          #to check null values

# df.isnull().sum()    #to check no of null values
# df.info() for information


DATA CLEANING
---------------At the time of cleaning first thing is--------------------
[imputation]handle missing values(numerical type,text based'string' type)--replace-missing-value
    [we find average of the values and place the value at the missing value place]
    for that we use logic(MEAN) and use library(SCIKIT-LEARN) Use class simpleimputer(finds the null and place the average of all values)

    [if missing value is text type]use logic(FREQUENCY) use any class in various ways]

[clean up]string cleaning[(string to numerical]type.. for a numerical col) we use STRING FUNCTIONS and should know pandas str functions
    we should know pandas str function,lambda expression, apply and applymap()

[row/columns remove] logic is DROP THE COL and library is PD.DROP()
[columns add] logic is (data to fill the columns)
[column renaming] library use ( pd.rename())
[row add] logic is (data fro the column)
[replace values in row/col] logic (data to replace) should know function (pd.replace())
[applymap works on row and column both not like that apply function.]


In [5]:
df

sno             name   age   salary     designation        mobile
0    1    shabeeh abaas  23.0  $20,000         manager  9.140098e+09
1    2  kashish agrawal  21.0  $23,000        manager   3.242343e+08
2    3     nisha shukla  22.0  $32,000  region manager  2.903482e+09
3    4     kriti rajput  22.0   $3,333             NaN           NaN
4    5     deepak gupta  23.0  $33,000         manager  2.343243e+08
5    6     mayank singh  23.0      NaN  region manager  2.334243e+08
6    7     aditya sagar   NaN  $23,333         manager  2.342423e+09
7    8         prashant  22.0   $3,333        director  2.324343e+07

cleaning function

In [6]:
def salary_clean(salary):
    if isinstance(salary,str): # to check type of the data
        salary=salary.strip()
        if '$' in salary:
            salary=salary.replace('$','')
        if ',' in salary:
            salary=salary.replace(',','')

        return int(salary)
    return salary

In [7]:
#for cleaning
# test run
df['salary'].apply(salary_clean)


0    20000.0
1    23000.0
2    32000.0
3     3333.0
4    33000.0
5        NaN
6    23333.0
7     3333.0
Name: salary, dtype: float64

In [8]:
#final apply
df['salary']=df['salary'].apply(salary_clean)
df

sno             name   age   salary     designation        mobile
0    1    shabeeh abaas  23.0  20000.0         manager  9.140098e+09
1    2  kashish agrawal  21.0  23000.0        manager   3.242343e+08
2    3     nisha shukla  22.0  32000.0  region manager  2.903482e+09
3    4     kriti rajput  22.0   3333.0             NaN           NaN
4    5     deepak gupta  23.0  33000.0         manager  2.343243e+08
5    6     mayank singh  23.0      NaN  region manager  2.334243e+08
6    7     aditya sagar   NaN  23333.0         manager  2.342423e+09
7    8         prashant  22.0   3333.0        director  2.324343e+07

removing column mobile

In [9]:
#test run       df.drop('['mobile','sno','name'],axis=1) #axis define column 
#if any col has same value or unique values then the column is worst
#(but it is not for the predictable col)

In [10]:
#actual run
df.drop(['mobile','sno','name'],axis=1,inplace=True)#inpalce makes the changes into the actual data
df

age   salary     designation
0  23.0  20000.0         manager
1  21.0  23000.0        manager 
2  22.0  32000.0  region manager
3  22.0   3333.0             NaN
4  23.0  33000.0         manager
5  23.0      NaN  region manager
6   NaN  23333.0         manager
7  22.0   3333.0        director

we fill missing values values by using (scikit learn library)


In [11]:
from sklearn.impute import SimpleImputer #simpleimputer works for the numbers to complete the missing values


In [12]:
#SimpleImputer? #it is the way to know about any function

PROCESS OF SCIKIT LEARN(general scheme)

FIRST WAY:(WHEN WE USE ALGORITHM)
1.)class instantiate(object create)
2.) fit the data into the object(fit fucntion to fit the data into object)
3.) transform to get the result(call the transform function)

SECOND WAY:PREPROCESSING(WHEN WE USE OUR DATA)
1.)class instantiate(object create)
2.)Fit_transfor() [to pass the data and get the result directly]

In [13]:
imputer=SimpleImputer()

In [14]:
#x is the columne y is the data
#trial run
cols=["age","salary"]
imputer.fit_transform(df[cols])

array([[2.30000000e+01, 2.00000000e+04],
       [2.10000000e+01, 2.30000000e+04],
       [2.20000000e+01, 3.20000000e+04],
       [2.20000000e+01, 3.33300000e+03],
       [2.30000000e+01, 3.30000000e+04],
       [2.30000000e+01, 1.97141429e+04],
       [2.22857143e+01, 2.33330000e+04],
       [2.20000000e+01, 3.33300000e+03]])

In [15]:
#main run
cols=["age","salary"]
df[cols]=imputer.fit_transform(df[cols])

In [16]:
df

age        salary     designation
0  23.000000  20000.000000         manager
1  21.000000  23000.000000        manager 
2  22.000000  32000.000000  region manager
3  22.000000   3333.000000             NaN
4  23.000000  33000.000000         manager
5  23.000000  19714.142857  region manager
6  22.285714  23333.000000         manager
7  22.000000   3333.000000        director

if any colomn should be predictable and their is a missing value then we drop that data from the data

*****
df.ndim (shows the no of dimenstion if it is 1d or 2d)

In [17]:
df['designation'].value_counts()

manager           3
region manager    2
manager           1
director          1
Name: designation, dtype: int64

In [18]:
imp2=SimpleImputer(strategy='most_frequent')
#imp2.fit_transform(df['designation'])       #it will show error of 1d array we need 2d array

In [19]:
df['designation']=imp2.fit_transform(df[['designation']])#now we solved the error and make 2d array by dataframe concept with two brackets
df

age        salary     designation
0  23.000000  20000.000000         manager
1  21.000000  23000.000000        manager 
2  22.000000  32000.000000  region manager
3  22.000000   3333.000000         manager
4  23.000000  33000.000000         manager
5  23.000000  19714.142857  region manager
6  22.285714  23333.000000         manager
7  22.000000   3333.000000        director

add a column of male female values

In [20]:
gender=['male','female']*4

In [21]:
df['gender']=gender
df

age        salary     designation  gender
0  23.000000  20000.000000         manager    male
1  21.000000  23000.000000        manager   female
2  22.000000  32000.000000  region manager    male
3  22.000000   3333.000000         manager  female
4  23.000000  33000.000000         manager    male
5  23.000000  19714.142857  region manager  female
6  22.285714  23333.000000         manager    male
7  22.000000   3333.000000        director  female

RENAME A column

In [22]:
df.rename({'salary':'pay'},axis=1,inplace=True)
df


age           pay     designation  gender
0  23.000000  20000.000000         manager    male
1  21.000000  23000.000000        manager   female
2  22.000000  32000.000000  region manager    male
3  22.000000   3333.000000         manager  female
4  23.000000  33000.000000         manager    male
5  23.000000  19714.142857  region manager  female
6  22.285714  23333.000000         manager    male
7  22.000000   3333.000000        director  female

adding row

In [23]:
df.loc[0]

age               23.0
pay            20000.0
designation    manager
gender            male
Name: 0, dtype: object

In [24]:
row=[{
    'age':19,
    'pay':33333,
    'designation':'manager',
    'gender':'male'
},
{
    'age':22,
    'pay':45333,
    'designation':'manager',
    'gender':'female'
}]


In [25]:
#if we use append the row then the data will add inproper way df.append(row)


#second way
df=df.append(row,ignore_index=True)
df


C:\Users\ASUS\AppData\Local\Temp\ipykernel_13248\530968075.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(row,ignore_index=True)


age           pay     designation  gender
0  23.000000  20000.000000         manager    male
1  21.000000  23000.000000        manager   female
2  22.000000  32000.000000  region manager    male
3  22.000000   3333.000000         manager  female
4  23.000000  33000.000000         manager    male
5  23.000000  19714.142857  region manager  female
6  22.285714  23333.000000         manager    male
7  22.000000   3333.000000        director  female
8  19.000000  33333.000000         manager    male
9  22.000000  45333.000000         manager  female

DATA SHOULD BE NUMERICAL for scikitlearn use

[ Techniques to convert the data into numerical format ]
1.) label encoder (data to numerical value)
2.) onehotencoder(dummy variable) , for same


#when we have binary values menas  two values then we use label encoder only


In [26]:
df['gender'].value_counts()


male      5
female    5
Name: gender, dtype: int64

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
#step 1 (creating object)
gender_enc=LabelEncoder()
gender_enc.fit(df['gender'])

LabelEncoder()

In [29]:
#second step transformation

df['gender']=gender_enc.transform(df['gender'])
df

age           pay     designation  gender
0  23.000000  20000.000000         manager       1
1  21.000000  23000.000000        manager        0
2  22.000000  32000.000000  region manager       1
3  22.000000   3333.000000         manager       0
4  23.000000  33000.000000         manager       1
5  23.000000  19714.142857  region manager       0
6  22.285714  23333.000000         manager       1
7  22.000000   3333.000000        director       0
8  19.000000  33333.000000         manager       1
9  22.000000  45333.000000         manager       0

In [30]:
gender_enc.classes_

array(['female', 'male'], dtype=object)

In [31]:
gender_enc.inverse_transform([1,0])

array(['male', 'female'], dtype=object)


if our data have multiple values then we use ONEHOTENCODER

In [32]:
df['designation'].value_counts()

manager           6
region manager    2
manager           1
director          1
Name: designation, dtype: int64

In [33]:
df.designation.unique()
#we have multiple unique value in data so we use onehotencoder

array(['manager', 'manager ', 'region manager', 'director'], dtype=object)

In [34]:
df.designation.nunique() #no of unique values

4

ONEHOTENCODER(dummy variable creation) hactic

assume we have two col and 10 rows
STATE                   AMOUNT
-------------------------------
newyork                 2324
sanfransisco            123
newyork                 45
sanfransisco            6 
newyork                 34
sanfransisco            67
sanfransisco            324
los angelas             3245
newyork                 222
los angelas             234

total unique value: 3
when we apply onehotencoder in state col then it make 3 diff col bcs here we have 3 unique values

---------------------------------------(these var are dummy variables)
los angelas         newyork         sanfransisco
-------------------------------------------------
0                   1               0
0                   0               1
0                   1               0
0                   0               1
0                   1               0
0                   0               1
0                   0               1
1                   0               0
0                   1               0
1                   0               0
(IT IS DUMMY VARIABLE CREATION OR HOT ENCODING)


In [35]:
from sklearn.preprocessing import OneHotEncoder

In [36]:
desig_enc=OneHotEncoder(drop='first')
#we need to two dimensional data
desig_enc.fit(df[['designation']]) #it creates an object for onehotencoder

OneHotEncoder(drop='first')

In [37]:
designation_dummies=desig_enc.transform(df[['designation']]).toarray() 
#toarray for converting it numpy array for display
#if it shows array in result then it is numpy matrix

now we need to concatinate dummy variables with orignal data
numpy matrix
---------
-   -   -
-   -   -
-   -   -
---------
    +
data frame
---------
-   -   -
-   -   -
-   -   -
---------


to do concatinate we do typeconversion(to data frame)

In [38]:
df.drop(columns=['designation'],axis=1,inplace=True)

In [39]:
df.values

array([[2.30000000e+01, 2.00000000e+04, 1.00000000e+00],
       [2.10000000e+01, 2.30000000e+04, 0.00000000e+00],
       [2.20000000e+01, 3.20000000e+04, 1.00000000e+00],
       [2.20000000e+01, 3.33300000e+03, 0.00000000e+00],
       [2.30000000e+01, 3.30000000e+04, 1.00000000e+00],
       [2.30000000e+01, 1.97141429e+04, 0.00000000e+00],
       [2.22857143e+01, 2.33330000e+04, 1.00000000e+00],
       [2.20000000e+01, 3.33300000e+03, 0.00000000e+00],
       [1.90000000e+01, 3.33330000e+04, 1.00000000e+00],
       [2.20000000e+01, 4.53330000e+04, 0.00000000e+00]])

In [40]:
#now we add two numpy matrix
import numpy as np

FOR ADDING MATRIX:
V STACK(NO OF COLUMN SHOULD BE SAME)
H STACK(NO OF ROW SHOULD BE SAME)


In [41]:
data=np.hstack((designation_dummies,df.values))

In [42]:
data.shape

(10, 6)

NOW NUMPY MATRIX TO DATA FRAME(BEST WAY) TO CONCATINATE DF TO DF

In [43]:
desig_dummy_df=pd.DataFrame(designation_dummies)
desig_dummy_df.head()

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0
3  1.0  0.0  0.0
4  1.0  0.0  0.0

In [44]:
data_df=pd.concat([desig_dummy_df,df],axis=1)

In [45]:
data_df.head() #now we have all numerical values 

0    1    2   age      pay  gender
0  1.0  0.0  0.0  23.0  20000.0       1
1  0.0  1.0  0.0  21.0  23000.0       0
2  0.0  0.0  1.0  22.0  32000.0       1
3  1.0  0.0  0.0  22.0   3333.0       0
4  1.0  0.0  0.0  23.0  33000.0       1

we need to drop the first col for the ml algo for humanity

SCALING THE DATA

(ml algo should undersatnd all the col important)
so we scale the column and give importance to all col

TWO METHODS TO SCALE:
1.) MINMAX SCALING
2.) STANDARD SCALING


In [46]:
a=np.array([23,45,23,65,43,22,112,2334])
#lets reduce the data and every value should lie between 0 to 1
 

In [47]:
a

array([  23,   45,   23,   65,   43,   22,  112, 2334])

In [48]:
a/a.max()

array([0.00985433, 0.01928021, 0.00985433, 0.02784919, 0.01842331,
       0.00942588, 0.04798629, 1.        ])

now we use scaling concept of sklearn for minmax scaling and standard scaling


In [49]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [50]:
mxScaler=MinMaxScaler()
mxScaler.fit(data_df)
scaled_data=mxScaler.transform(data_df)
print(scaled_data)

[[1.         0.         0.         1.         0.39683333 1.        ]
 [0.         1.         0.         0.5        0.4682619  0.        ]
 [0.         0.         1.         0.75       0.68254762 1.        ]
 [1.         0.         0.         0.75       0.         0.        ]
 [1.         0.         0.         1.         0.70635714 1.        ]
 [0.         0.         1.         1.         0.39002721 0.        ]
 [1.         0.         0.         0.82142857 0.47619048 1.        ]
 [0.         0.         0.         0.75       0.         0.        ]
 [1.         0.         0.         0.         0.71428571 1.        ]
 [1.         0.         0.         0.75       1.         0.        ]]


C:\Users\ASUS\miniconda3\envs\digi1\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\ASUS\miniconda3\envs\digi1\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [51]:
#this is used in coding
stdScaler=StandardScaler()
stdScaler.fit(data_df)
scaled_data=stdScaler.transform(data_df)
print(scaled_data)

[[ 0.81649658 -0.33333333 -0.5         0.93860057 -0.2897882   1.        ]
 [-1.22474487  3.         -0.5        -0.81345383 -0.05081484 -1.        ]
 [-1.22474487 -0.33333333  2.          0.06257337  0.66610524  1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.06257337 -1.61744454 -1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.93860057  0.74576303  1.        ]
 [-1.22474487 -0.33333333  2.          0.93860057 -0.31255895 -1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.31286686 -0.0242888   1.        ]
 [-1.22474487 -0.33333333 -0.5         0.06257337 -1.61744454 -1.        ]
 [ 0.81649658 -0.33333333 -0.5        -2.56550822  0.77228907  1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.06257337  1.72818252 -1.        ]]


C:\Users\ASUS\miniconda3\envs\digi1\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
C:\Users\ASUS\miniconda3\envs\digi1\lib\site-packages\sklearn\utils\validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


In [52]:
print(scaled_data)

[[ 0.81649658 -0.33333333 -0.5         0.93860057 -0.2897882   1.        ]
 [-1.22474487  3.         -0.5        -0.81345383 -0.05081484 -1.        ]
 [-1.22474487 -0.33333333  2.          0.06257337  0.66610524  1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.06257337 -1.61744454 -1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.93860057  0.74576303  1.        ]
 [-1.22474487 -0.33333333  2.          0.93860057 -0.31255895 -1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.31286686 -0.0242888   1.        ]
 [-1.22474487 -0.33333333 -0.5         0.06257337 -1.61744454 -1.        ]
 [ 0.81649658 -0.33333333 -0.5        -2.56550822  0.77228907  1.        ]
 [ 0.81649658 -0.33333333 -0.5         0.06257337  1.72818252 -1.        ]]


-----------------SUPERVISED ML ALGO-------------

---------------------------
- AGE  - BRAND    - PRICE -
- 3    - balentine- $200  -
- 12   - sapphire - $600  -
- 50   - sapphire -   ?   -
---------------------------

->price is the predictable col(response)output or label
->age and brand is the input col(feaures)independent col

if our data has input and output data both availble then we can perform 
SUPERVISED LEARNING.

INPUT COL  -> X
OUTPUT COL -> Y

NOTE: IF OUR DATA DONT HAVE PREDICTABLE COL THEN IT IS UNSUPERVISED DATA.


                            SUPERVISED ML ALGO
If prediciton column contains changing numerical values: REGRESSION
If prediciton column contains similar categorical values(male/female, 0/1): CLASSIFICATION



:::::FIRST WE LEARN **REGRESSION:::::

SUPREVISED REGRESSION ALGORITHMS->

1.) LINEAR REGRESSION
    *simple linear regression(when we have simple data less column)
    *multiple linear regression(if input colmns are big)
    *polynomial linear regression(when parabolic data or expnential data)

2.) DECISION TREE ALGOS (Many trees)
    *decision tree regression
    *decision tree classification

3.) RANDOM FOREST ALGO(ensemble)

4.) SUPPORT VECTOR MACHINE (SVM)

5.)XGboost ALGO (HOW REGRESSION AND CLASSIFICATION WORKS)
