In [86]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [87]:
import numpy as np
np.set_printoptions(precision=2)

In [88]:
df=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [89]:
df.drop(['Name','Cabin','Ticket','Fare'],axis=1,inplace=True)
df

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0              1         0       3    male  22.0      1      0        S
1              2         1       1  female  38.0      1      0        C
2              3         1       3  female  26.0      0      0        S
3              4         1       1  female  35.0      1      0        S
4              5         0       3    male  35.0      0      0        S
..           ...       ...     ...     ...   ...    ...    ...      ...
886          887         0       2    male  27.0      0      0        S
887          888         1       1  female  19.0      0      0        S
888          889         0       3  female   NaN      1      2        S
889          890         1       1    male  26.0      0      0        C
890          891         0       3    male  32.0      0      0        Q

[891 rows x 8 columns]

In [90]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Embarked         2
dtype: int64

In [91]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer()
imputer.fit_transform(df[['Age']]) #test run

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [29.7 ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [29.7 ],
       [31.  ],
       [29.7 ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [29.7 ],
       [19.  ],
       [29.7 ],
       [29.7 ],
       [40.  ],
       [29.7 ],
       [29.7 ],
       [66.  ],
       [28.  ],
       [42.  ],
       [29.7 ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [29.7 ],
       [ 3.  ],
       [19.  ],
       [29.7 ],
       [29.7 ],
       [29.7 ],
       [29.7 ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [29.7 ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [92]:
df['Age']=imputer.fit_transform(df[['Age']])

In [93]:
df.isnull().sum()


PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       2
dtype: int64

In [94]:
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0            1         0       3    male  22.0      1      0        S
1            2         1       1  female  38.0      1      0        C
2            3         1       3  female  26.0      0      0        S
3            4         1       1  female  35.0      1      0        S
4            5         0       3    male  35.0      0      0        S

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Embarked     889 non-null    object 
dtypes: float64(1), int64(5), object(2)
memory usage: 55.8+ KB


In [96]:
imputer2=SimpleImputer(strategy='most_frequent')

In [97]:
df["Embarked"]=imputer2.fit_transform(df[["Embarked"]])

In [98]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Embarked       0
dtype: int64

In [99]:
df.value_counts("Embarked")

Embarked
S    646
C    168
Q     77
dtype: int64

In [100]:
from sklearn.preprocessing import LabelEncoder
gender_enc=LabelEncoder()
gender_enc.fit(df["Sex"])

LabelEncoder()

In [101]:
gender_enc.transform(df["Sex"])

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,

In [102]:
df["Sex"]=gender_enc.transform(df["Sex"])

In [103]:
from sklearn.preprocessing import OneHotEncoder
Embarked_enc=OneHotEncoder(drop="first")
Embarked_enc.fit(df[['Embarked']])

OneHotEncoder(drop='first')

In [104]:
Embarked_dummies=Embarked_enc.transform(df[['Embarked']]).toarray()
Embarked_dummies

array([[0., 1.],
       [0., 0.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 0.],
       [1., 0.]])

In [105]:
df.drop(columns=['Embarked'],axis=1,inplace=True)

In [106]:
import numpy as np
data=np.hstack((Embarked_dummies,df.values))
data.shape

(891, 9)

In [107]:
Embarked_dummies_df=pd.DataFrame(Embarked_dummies)
Embarked_dummies_df.head()

0    1
0  0.0  1.0
1  0.0  0.0
2  0.0  1.0
3  0.0  1.0
4  0.0  1.0

In [108]:
data_df=pd.concat([Embarked_dummies_df,df],axis=1)

In [109]:
data_df

0    1  PassengerId  Survived  Pclass  Sex        Age  SibSp  Parch
0    0.0  1.0            1         0       3    1  22.000000      1      0
1    0.0  0.0            2         1       1    0  38.000000      1      0
2    0.0  1.0            3         1       3    0  26.000000      0      0
3    0.0  1.0            4         1       1    0  35.000000      1      0
4    0.0  1.0            5         0       3    1  35.000000      0      0
..   ...  ...          ...       ...     ...  ...        ...    ...    ...
886  0.0  1.0          887         0       2    1  27.000000      0      0
887  0.0  1.0          888         1       1    0  19.000000      0      0
888  0.0  1.0          889         0       3    0  29.699118      1      2
889  0.0  0.0          890         1       1    1  26.000000      0      0
890  1.0  0.0          891         0       3    1  32.000000      0      0

[891 rows x 9 columns]

FEATURE SELECTION

In [110]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [111]:
featSelector=SelectKBest(chi2,k=2)

In [112]:
X=df.iloc[:,:-1]
print(X.shape)
y=df['Survived']
print(y.shape)

(891, 6)
(891,)


In [113]:
featSelector.fit(X,y)

SelectKBest(k=2, score_func=<function chi2 at 0x0000023104451E50>)

In [114]:
np.set_printoptions(precision=2)

In [115]:
featSelector.scores_

array([  3.31, 549.  ,  30.87,  92.7 ,  24.69,   2.58])

In [116]:
print(f"COL{featSelector.feature_names_in_}\n SEL{featSelector.get_feature_names_out()}")


COL['PassengerId' 'Survived' 'Pclass' 'Sex' 'Age' 'SibSp']
 SEL['Survived' 'Sex']


In [117]:
features=df[['Pclass','Sex','Age']]
#print(features.shape)

In [118]:
#
# print(featSelector.get_feature_names_out())
features

Pclass  Sex        Age
0         3    1  22.000000
1         1    0  38.000000
2         3    0  26.000000
3         1    0  35.000000
4         3    1  35.000000
..      ...  ...        ...
886       2    1  27.000000
887       1    0  19.000000
888       3    0  29.699118
889       1    1  26.000000
890       3    1  32.000000

[891 rows x 3 columns]

In [119]:
scaler=StandardScaler()
scaledX=scaler.fit_transform(features)
xtrain,xtest,ytrain,ytest=train_test_split(scaledX,y,test_size=.2,random_state=1)
m=KNeighborsClassifier(n_neighbors=9)
m.fit(xtrain,ytrain)
ypred=m.predict(xtest)
cm=confusion_matrix(ytest,ypred)
print(cm)

[[92 14]
 [31 42]]


In [120]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.75      0.87      0.80       106
           1       0.75      0.58      0.65        73

    accuracy                           0.75       179
   macro avg       0.75      0.72      0.73       179
weighted avg       0.75      0.75      0.74       179



wrapper method